name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install test dependencies
        run: pip install requests

      - name: Build and run Docker container
        run: |
          docker build -t fraud-detection-api .
          docker run -d --name my-api -p 8000:8000 fraud-detection-api

      - name: Run API tests
        run: |
          pip install pytest
          pytest tests/